### ISSUE TITLE
The repository does not have a Release 

### ISSUE THREAD

**Issue by mphat10** [pantheon-tweaks/pantheon-tweaks#111]
Err:14 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by ryonakano** [comment]
Pantheon Tweaks only supports elementary OS 6 which built on Ubuntu 20.04 LTS (focal). We won't support elementary OS 5.x or below.

Closing as "won't fix".
