### ISSUE TITLE
"Reset to default" always sets stylesheet to blueberry

### ISSUE THREAD

**Issue by delight-aug** [pantheon-tweaks/pantheon-tweaks#112]
I chose automatic wallpaper-based accent color in the Desktop's Appearance tab. But, when I click the "Reset to default" button — it always changes the stylesheet to blueberry. 

P.S. After that, if I look into the Desktop's Appearance tab — it still says I'm on "Automatic based on wallpaper" accent color.

**Comment by ryonakano** [comment]
Actually the default stylesheet is blueberry and this behavior should be correct. One thing we need to fix is that we should change selection in Desktop Plug from auto to blueberry.
