### ISSUE TITLE
How do I make the topbar transparent when the app is full of windows?

### ISSUE THREAD

**Issue by viethungspy** [pantheon-tweaks/pantheon-tweaks#136]
![image](https://user-images.githubusercontent.com/33823245/144742624-5da3d38e-ae3e-4ce1-b5ff-d0c18cf061e3.png)
I want to keep the top bar transparent when zooming in on apps, I can't find this setting in tweak. Help me

**Comment by ryonakano** [comment]
Hi, thanks for using Pantheon Tweaks! Unfortunately the current version of Tweaks don't support changing color of the panel, but I guess you can use the following tip:

https://elementaryos.stackexchange.com/questions/22613/change-wingpanel-color

**Comment by viethungspy** [comment]
Thanks @ryonakano, I will try it.
