### ISSUE TITLE
Typo "namaes"

### ISSUE THREAD

**Issue by hugok79** [pantheon-tweaks/pantheon-tweaks#147]
https://github.com/pantheon-tweaks/pantheon-tweaks/blob/ad0720986ab0fd4c25b76398e7a9ad11024f69da/po/pantheon-tweaks-plug.pot#L45

**Comment by ryonakano** [comment]
Good eyes!

**Comment by ryonakano** [comment]
Fixed in 3f60b29, thanks for pointing out this!
