### ISSUE TITLE
Animations tweaks do nothing and should be removed

### ISSUE THREAD

**Issue by andrewdbate** [pantheon-tweaks/pantheon-tweaks#151]
All of the settings on the _Animations_ pane have no effect and should be removed:
![Screenshot from 2022-04-04 23 18 55](https://user-images.githubusercontent.com/2998569/161641415-069bb8c5-f727-4f57-b5e4-0b2fd89e7d63.png)

Looking at the source code [here](https://github.com/pantheon-tweaks/pantheon-tweaks/blob/27729e809b84bd9e8461c37973a15285ddc62d73/src/Panes/AnimationsPane.vala), I can see that these settings correspond to the keys `open-duration`, `close-duration`, `snap-duration`, `minimize-duration` and `workspace-switch-duration` within the `org.pantheon.desktop.gala.animations` schema.

Looking at these in the dconf Editor, the description of each of these says that they are deprecated and that the key is ignored. Trying this out by changing the value of any of these keys and seeing what happens shows that they really do have no effect.

Screenshots from dconf Editor:
![Screenshot from 2022-04-04 22 51 46](https://user-images.githubusercontent.com/2998569/161642331-77410147-f99b-490c-bae4-e9b697fbf181.png)
![Screenshot from 2022-04-04 22 51 54](https://user-images.githubusercontent.com/2998569/161642338-01d997eb-cb31-4c82-a1dd-762c881c0159.png)
![Screenshot from 2022-04-04 22 52 18](https://user-images.githubusercontent.com/2998569/161642340-0d0f13db-40e1-4596-9e0c-230e8f3804c4.png)
![Screenshot from 2022-04-04 22 52 26](https://user-images.githubusercontent.com/2998569/161642353-883c6e2d-732e-444d-ba10-d08d28933947.png)
![Screenshot from 2022-04-04 22 52 38](https://user-images.githubusercontent.com/2998569/161642362-38a2936f-fe7e-4904-b069-d094bc4ae082.png)

I was somewhat confused at first why changing any of the settings on the Animations pane did nothing, until I looked into the source code. I think the best thing to do is to remove the Animations pane entirely since it doesn't do anything useful in elementary OS 6/6.1.

Thanks!

**Comment by ryonakano** [comment]
Thank you for your report! As you said these keys seem to be unused over three years ago so we can completely remove the Animations pane itself: https://github.com/elementary/gala/commit/50694796d4c8f0ca92517d5a628b0efdf748279c
