### ISSUE TITLE
Cant add repository

### ISSUE THREAD

**Issue by pwnedurl** [pantheon-tweaks/pantheon-tweaks#159]
please help

Err:9 https://ppa.launchpadcontent.net/philip.scott/pantheon-tweaks/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/philip.scott/pantheon-tweaks/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by pwnedurl** [comment]
> 

Err:9 https://ppa.launchpadcontent.net/versable/elementary-update/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/versable/elementary-update/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by pwnedurl** [comment]
> @pwnedurl I guess you tried installing Pantheon Tweaks on elementary OS 7 Early Access, right? Then I can confirm this error happening because we provide Pantheon Tweaks only for elementary OS 6.x at the moment. However OS 7 should be released at some time, of course, so we should provide it for OS 7 too at some point, thank you for your reminder.
> 
> However I don't have permission to perform this operation unfortunately, so I'll ask it for the original author of Pantheon Tweaks.
> 
> @Philip-Scott Could you enable PPA on Launchpad for Jammy which will be the base version of elementary OS 7?

@ryonakano indeed, and thanks for you reply

**Comment by Philip-Scott** [comment]
Hey @ryonakano I've enabled building for Jammy, and a triggered a manual build of pantheon-tweaks! :) The build has been successful and should be in the mirrors in a few hours. 

Let me know if you need anything else! Happy to help :) 

https://code.launchpad.net/~philip.scott/+recipe/pantheon-tweaks-git

@pwnedurl, please let us know if you hit this or other problems!

**Comment by ryonakano** [comment]
Hi @Philip-Scott, thank you for your quick response! I confirmed I can install Pantheon Tweaks on my installation of elementary OS 7 Early Access. :tada:

**Comment by joe733** [comment]
Hi, I'm testing elementaryOS 7. When I'm trying to add the PPA, it fails. Here are the commands that I ran:

```console
$ sudo apt install -y software-properties-common # no errors
$ sudo apt update # no errors
$ sudo add-apt-repository -y ppa:philip.scott/pantheon-tweaks
ERROR: ppa 'philip.scott/pantheon-tweak' not found (use --login if private)
```

**Comment by ryonakano** [comment]
@joe733
I tried the command above on my Horus and the PPA added succesfully.

Did you correctly typed the name of PPA? According to the error message you seemed to missed the trailing "s": `ERROR: ppa 'philip.scott/pantheon-tweak' not found`

**Comment by joe733** [comment]
Ah my bad :man_facepalming:. Thanks!
