### ISSUE TITLE
Show tabs for files

### ISSUE THREAD

**Issue by Obema12** [pantheon-tweaks/pantheon-tweaks#164]
Could you make a similar function to show tabs for files like it's done for terminal tabs?

**Comment by ryonakano** [comment]
Good idea, but it's hardcoded to always show tabs in Files side:

https://github.com/elementary/files/blob/3553afaba24ec5af844a67d4dedf3d312ad6611f/src/View/Window.vala#L244

which means we have no control of this. Closing as "out of scope".
