### ISSUE TITLE
Updated icons

### ISSUE THREAD

**Issue by TomiOhl** [pantheon-tweaks/pantheon-tweaks#166]
Would be nice to have redesigned icons. The current ones are very old and don't look good in the more modern, simpler OS 6/7 environments.

**Comment by hrstwn** [comment]
I tried making one.
Here's it (center) compared to elementary's preferences-desktop and the old one
![image](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/2234449/a97a61aa-574a-435a-b56e-6686d6fdce78)

**Comment by TomiOhl** [comment]
Noice! Looks good but what needs an update even more badly are the icons in the sidebar when you open the Tweaks pane

**Comment by ryonakano** [comment]
> what needs an update even more badly are the icons in the sidebar when you open the Tweaks pane

The icons in the sidebar are elementary icons so report to https://github.com/elementary/icons/issues if they don't look good.

**Comment by ryonakano** [comment]
@TomiOhl Which icon in the sidebar do you feel bad specifically?

![スクリーンショット 2023-10-14 19 53 12](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/c0fb0490-19a1-40b4-be20-1d7543d563b3)

And what do you feel about changing like this?

![スクリーンショット 2023-10-14 19 52 09](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/3d8b6630-65f0-4378-bfb4-64a7b8ccb1aa)

**Comment by TomiOhl** [comment]
The three icons under the General category, especially Appearance and Miscellaneous. The changes you proposed are much much better imo! Since appearance is mostly desktop-related, the desktop icon is appropriate. Miscellaneous is a difficult concept, a quick search suggests using three dots or a clover-like symbol ([link](https://thenounproject.com/search/icons/?q=other), [link](https://graphicdesign.stackexchange.com/questions/76066/is-there-a-symbol-for-the-concept-of-other)), but a puzzle also makes sense since it implies something like "extensions" which is not far from the same meaning.
First I thought the fonts icon is also outdated, but in the context of the new icons it doesn't feel out of place.

**Comment by ryonakano** [comment]
Thank you very much for your opinion! I'll commit and push the proposal above then.
