### ISSUE TITLE
Compile the program for ARM64

### ISSUE THREAD

**Issue by HaroleDev** [pantheon-tweaks/pantheon-tweaks#182]
I was trying to install pantheon-tweaks through the PPA only to realize that it is only compiled for AMD64. While it is nice that I can compile myself, wouldn't it be nice to get that compiled straight to the PPA?

**Comment by ryonakano** [comment]
The source code itself doesn't depend on architectures, the only thing we need to do is to set up the PPA for ARM64, but unfortunately I have no permission to do that.

@Philip-Scott Could you set up your PPA of pantheon-tweaks ready for ARM64 with the following steps?

1. Log in to Launchpad
2. Open https://code.launchpad.net/~philip.scott/+recipe/pantheon-tweaks-git and click "Change details" from the right menu
![スクリーンショット 2023-10-10 20 47 11](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/c382fdf1-5b0a-4d37-a60c-2f2ff7a1abf2)
3. Under "Processors:" section, check the "ARM ARMv8 (arm64)" checkbox like the following screenshot
![スクリーンショット 2023-10-10 20 30 50](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/40c6419d-7666-4a37-a8f2-dbd739839760)

**Comment by Philip-Scott** [comment]
Done! Let me know if this doesn't do the trick :)

**Comment by ryonakano** [comment]
It seems to be available now. Thank you for setting PPA up @Philip-Scott and reporting issue @HaroleDev!

![スクリーンショット 2023-10-28 07 19 12](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/65c22d16-246e-4d85-9ade-28e09145fdf9)
