### ISSUE TITLE
Pantheon Tweaks as an independent GTK app provided through Flatpak

### ISSUE THREAD

**Issue by ryonakano** [pantheon-tweaks/pantheon-tweaks#187]
@Philip-Scott What do you think about making Pantheon Tweaks an independent GTK app instead of Switchboard plugin, and providing it using Flatpak instead of PPA? Or should we keep as it is?

### Problem

I think the current Tweaks have some problems:

- Not easy and not recommended way to install.
    - Tweaks is provided through PPA and requires add-apt-repository command, which is not a recommended way to install apps by elementary team.
- Depends on Switchboard heavily since Tweaks is its plugin.
    - We cannot port to GTK4 nor use Flatpak until Switchbnoard itself begins to use them.
    - Tweaks would die if elementary team drop plugin feature from Switchboard.
- Difficult to support multiple elementary OS versions.
    - Some users report "can't install" issue like #61 due to older dependency version, etc.
    - It's difficult to keep supporting multiple elementary OS major versions if there are API breaking changes.
- Sometimes PPA management is required.
    - which needs operations out of this repository / GitHub.
    - e.g. #182 or https://github.com/elementary-tweaks/elementary-tweaks/issues/127

### Fix

To resolve these issues above, I think we may want to:

- Make Tweaks an independent app instead of a plugin of Switchboard.
    - which allows us to port to GTK4 anytime soon.
- Provide Tweaks using Flatpak instead of .deb file / PPA.
    - Flatpak is recommended by elementary team and easy to install.
    - No need to consider differencies of host OS version.

I've created an experiment branch [`research/as-independent-app`](https://github.com/pantheon-tweaks/pantheon-tweaks/tree/research/as-independent-app) to confirm possibility of implementation. If possible, I'd like you to install and try this branch on elementary OS. I'll create a  pull request from this branch with additional fix (e.g. README things) if you agree with changing to independent Flatpak app.

```
$ flatpak-builder build --user --install --force-clean --install-deps-from=appcenter com.github.pantheon-tweaks.pantheon-tweaks.yml
$ flatpak run com.github.pantheon_tweaks.pantheon-tweaks
```

![image](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/65199ee1-f125-497a-b3d1-3464eb954fec)

**Comment by Philip-Scott** [comment]
Hey good plan man, I think it's a good idea to future proof it and it would have the side effect to also make it portable across other OSs without having to depend on Switchboard :) 

I was under the impressions that Flatpacks could not modify system settings though, but you got it working, was there a portal/permissions to allow that access?

After this time, I trust that you know what is best for this project, and I will support you in this decision :) 

I'll setup a VM with elementary to give your branch a test spin, and when the time comes let me know and I can pull the plug to the PPA to avoid having broken builds

**Comment by ryonakano** [comment]
Thank you for your comment. I'll begin to work on porting Tweaks to the flatpacked GTK app.

> it would have the side effect to also make it portable across other OSs without having to depend on Switchboard :)

Yes, you're right. Porting Tweaks into just a normal GTK app also means it can be launched and may break preferences on other desktop environments accidentally, but I think the following things should prevent that:

- Do not show the Tweaks icon in the app launcher if not Pantheon. This can be fulfilled by setting `OnlyShowIn=Pantheon` in the .desktop file (and [already done](https://github.com/pantheon-tweaks/pantheon-tweaks/blob/85b6f3d82fc7931f608172d16594dca0254be9e7/data/pantheon-tweaks.desktop.in#L11) in the experiment branch).
- Check if the current desktop environment is Pantheon on runtime in case a user tries to launch Tweaks from terminal, not from the app launcher. This is not implemented in the experiment branch yet (I forgot to consider :dizzy_face: ) but can be fulfilled just by cheking if `GLib.Environment.get_variable ("XDG_CURRENT_DESKTOP")` returns `Pantheon`. (FYI it returns `ubuntu:GNOME` on Ubuntu 23.10)

> I was under the impressions that Flatpacks could not modify system settings though, but you got it working, was there a portal/permissions to allow that access?

Yes I was also wondering that. There does not seem to a portal exists here, but dconf-editor which also read/write system GSettings is [available on Flathub](https://github.com/flathub/ca.desrt.dconf-editor) and they do the following things to fulfill that:

- Create [a wrapper script](https://github.com/flathub/ca.desrt.dconf-editor/blob/d41b28448c20035f8d97622d214fc8d6da0daa3b/start-dconf-editor.sh) to launch the app
    - Create a symlink to the system's GSettings file in the sandboxed directory before launching the app and append it to  `XDG_DATA_DIRS` environment variable
    - FYI `GLib.Settings` uses `XDG_DATA_DIRS` by default according to [the example code on Valadoc](https://valadoc.org/gio-2.0/GLib.Settings.html)
- [Patch dconf](https://github.com/flathub/ca.desrt.dconf-editor/blob/d41b28448c20035f8d97622d214fc8d6da0daa3b/dconf-override.patch)
    - The patched code is opening "user-db" of dconf located in `~/.config/dconf/user` using `g_get_user_config_dir ()`. However, this function returns the path in the sandbox on Flatpak app.
    - So this patch makes sure to use the host's path instead if sandboxed.

> I'll setup a VM with elementary to give your branch a test spin, and when the time comes let me know and I can pull the plug to the PPA to avoid having broken builds

Thank you. Regarding to the PPA, maybe we need to modify debian packaging to install the new flatpaked Tweaks app instead of the Plug like elementary did [here](https://github.com/elementary/screenshot/commit/2db3e72f72b791ec8f50d57cf135a52a6ff5a2ac) in case if a user still attempts a PPA installation. I'll also implement this too.

**Comment by ryonakano** [comment]
@Philip-Scott One thing I'd like to confirm, do we submit the flatpaked Tweaks to AppCenter or keep it self-hosted?

I read https://github.com/elementary-tweaks/elementary-tweaks/issues/48#issuecomment-306370803 and you're right. Tweaks still read/write system preferences even if it is sandboxed, thus might break system. (also I'm not sure if it's accepted to AppCenter since we need some file access permissions)

Looks like we can create a repo on GitHub according to [the doc](https://docs.flatpak.org/en/latest/hosting-a-repository.html#hosting-a-repository-on-gitlab-github-pages) in case of self-hosted.

**Comment by Philip-Scott** [comment]
Yeah.... I don't think this will ever be accepted on AppCenter :sweat_smile: Danielle has always been pretty opposed to tweaks as it can lead to things breaking. I think just hosting on Flathub can be more than enough :) 

One thing that would be cool however is if we could get this to be installed on a clean elementary OS build without a user needing to open the terminal at all! [Steam-deck-utilities](https://github.com/CryoByte33/steam-deck-utilities) and [Emudeck](https://www.emudeck.com/#download) to this by getting the user to download a .desktop file that when executed, downloads and runs a bash script. Just something to consider ;) 

I don't know if things could break for existing users if we were to update the PPA to download and install the flatpak... Maybe we can just pause it for now to make things easier and avoid any edge cases :thinking: What do you think?

**Comment by ryonakano** [comment]
> Yeah.... I don't think this will ever be accepted on AppCenter 😅 Danielle has always been pretty opposed to tweaks as it can lead to things breaking. I think just hosting on Flathub can be more than enough :)

You're right. We can submit to Flathub instead.

> One thing that would be cool however is if we could get this to be installed on a clean elementary OS install without a user needing to open the terminal at all! [Steam-deck-utilities](https://github.com/CryoByte33/steam-deck-utilities) and [Emudeck](https://www.emudeck.com/#download) do this by getting the user to download a .desktop file that when executed, downloads and runs a bash script. Just something to consider ;)

elementary OS comes with a tool named [Sideload](https://github.com/elementary/sideload) that can install Flatpak apps, so it should work. Flathub provides `.flatpakref` file for each app, so users just download it, open it in the file manager, and then Sideload is shown like the below screenshot. Installing Flatpak app from `.flatpakref` also registers Flathub as an app remote, so users can retrieve updates after that time.

![VirtualBox_elementary OS_07_01_2024_08_39_26](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/d74b2782-6444-4999-ab1c-4df313a50769)

> I don't know if things could break for existing users if we were to update the PPA to download and install the flatpak... Maybe we can just pause it for now to make things easier and avoid any edge cases 🤔 What do you think?

Indeed, just pausing the PPA would lessen risks of "it won't work" issue happening and our tasks. Before pausing PPA, maybe we may want to let users know about the migration to an independent app through the plug? For example, adding a infobar about migration like [this](https://github.com/elementary/switchboard-plug-a11y/blob/main/data/screenshot-audio.png), ship that change as the last update, then pause the PPA.

**Comment by ryonakano** [comment]
> Before pausing PPA, maybe we may want to let users know about the migration to an independent app through the plug? For example, adding a infobar about migration like [this](https://github.com/elementary/switchboard-plug-a11y/blob/main/data/screenshot-audio.png), ship that change as the last update, then pause the PPA.

@Philip-Scott I added the infobar to the Tweaks, triggers builds on Launchpad, and it succeeded.

Could you pause the PPA? I guess changing "Build schedule" to "Build on request" in the following page should work.

https://code.launchpad.net/~philip.scott/+recipe/pantheon-tweaks-git

**Comment by Philip-Scott** [comment]
PPA has been paused! 

![image](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/10786508/b052687a-4d69-4d72-9646-51a37f93c166)
