### ISSUE TITLE
Remove PlankPane?

### ISSUE THREAD

**Issue by ryonakano** [pantheon-tweaks/pantheon-tweaks#24]
I guess we may want to remove PlankPane because:

- it's not used and shown in the plug at the moment because it's commented out
- the settings code in PlankSettings.vala is old and; it try to load a keyfile of Plank, while they use GSettings now
- Plank can be configured by right-clicking the dock or run `plank --preferences`
- no user complains about missing of a preference page for Plank

@Philip-Scott What do you think?

**Comment by Philip-Scott** [comment]
It may be cool if the plank pane became a "plank manager" to manage multiple instances of plan that you can launch via `plan -n "dockName"` and have their respective `plank --preferences` open up from there. But yeah for now we can just kill the current code :)
