### ISSUE TITLE
Redesign App

### ISSUE THREAD

**Issue by alainm23** [pantheon-tweaks/pantheon-tweaks#244]
Hello, thank you for keeping this project active.

Hi, I feel that Tweaks has been left in the past, is there a possibility to redesign it?

**Comment by ryonakano** [comment]
How about this design? This is the latest main branch that I'm going to release in this weekend:

![スクリーンショット 2024-09-20 16 47 06](https://github.com/user-attachments/assets/7b1d2025-8ee6-4287-bbff-530e5cc7ba5c)
![スクリーンショット 2024-09-20 16 47 40](https://github.com/user-attachments/assets/4e529cfb-5980-4857-91cd-25bc63e7d341)

**Comment by alainm23** [comment]
Looks great, good job.
