### ISSUE TITLE
Installation error: Unable to add the PPA

### ISSUE THREAD

**Issue by AndreasTNT** [pantheon-tweaks/pantheon-tweaks#38]
Hi, I recently installed Elementary OS 5.1 Hera in a VM on Oracle VirtualBox 6.1.
Wanted to enable a dark theme, using the "prefer the dark variant" slider in tweaks.
And I got an error

 Terminal log attached in file
[Github-Issue-Report-Pantheon-Tweaks.txt](https://github.com/pantheon-tweaks/pantheon-tweaks/files/5433948/Github-Issue-Report-Pantheon-Tweaks.txt)

**Comment by AndreasTNT** [comment]
If you want more information, just ask!

**Comment by famellad** [comment]
Getting the exact same output, the repo simply does not get added and the target `pantheon-tweaks` does **not** exist later when doing the `apt install` step

**Comment by ryonakano** [comment]
Pantheon Tweaks is only provided for elementary OS 6 (which is available as an early access build) as written in README. You can't install it on elementary OS 5.x from PPA.

**Comment by AndreasTNT** [comment]
Oh . Did not see that in the readme. 
How can it be updated?

**Comment by ryonakano** [comment]
You can get it from https://builds.elementary.io.

**Comment by AndreasTNT** [comment]
Ok, thanks
