### ISSUE TITLE
Impossible to install without sources

### ISSUE THREAD

**Issue by MrZyr0** [pantheon-tweaks/pantheon-tweaks#39]
![image](https://user-images.githubusercontent.com/32927775/97113268-6c97a280-16e9-11eb-8a37-382cca5b3211.png)

**Comment by AndreasTNT** [comment]
Possible same issue as in https://github.com/pantheon-tweaks/pantheon-tweaks/issues/38

**Comment by AndreasTNT** [comment]
> Possible same issue as in [this issue](https://github.com/pantheon-tweaks/pantheon-tweaks/issues/38)

Philip Scott discussing an possible alternative installation method 

https://github.com/pantheon-tweaks/pantheon-tweaks/issues/5

**Comment by Philip-Scott** [comment]
Nope, Pantheon-Tweaks is only available for elementary OS 6, based on Focal. What @MrZyr0 is looking for is elementary Tweaks since he has an older version of elementary. I will open an issue to make this more clear on the readme

https://github.com/elementary-tweaks/elementary-tweaks/

**Comment by MrZyr0** [comment]
Aaah okay. I didn't realize I was on version 5.
It's the most recent one you can get on the official website.
So I have to use "elementary tweaks" right?

**Comment by ryonakano** [comment]
@MrZyr0 Yes, you need to use elementary Tweaks on elementary OS 5.x or before and switch to Pantheon Tweaks when elementary OS 6 is released.
