### ISSUE TITLE
Elementary Tweaks Install issues (5.1.7 Hera) (LEGACY)

### ISSUE THREAD

**Issue by phoenix277yt** [pantheon-tweaks/pantheon-tweaks#41]
So since the elementary tweaks github page is archived I decided to post the issue here. Note - I've tried all solutions in that github page by-far and also the new simplified installation instructions, yet the problem persists.
`Err:11 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Err:12 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by ryonakano** [comment]
Hmm according to the log, you seem to add a PPA of Pantheon Tweaks, not elementary Tweaks. Pantheon Tweaks only supports the next major version of elementary OS so you need to use elementary Tweaks on Hera and switch to Pantheon Tweaks when the new version of elementary OS is released.

If you mean to add the PPA of elementary OS, it looks like a temporary network issue. Try `sudo apt update` after a while

**Comment by phoenix277yt** [comment]
@ryonakano here's a full log, im using the command for the ppa installation of the legacy option.
`$ sudo add-apt-repository ppa:philip.scott/elementary-tweaks
[sudo] password for daksh:           
 system settings panel for elementary OS that lets you easily and safely customise your desktop's appearance  https://github.com/elementary-tweaks/elementary-tweaks
 More info: https://launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://in.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                          
Hit:3 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                          
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                                   
Hit:5 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                
Get:6 http://packages.elementary.io/appcenter bionic InRelease [5,909 B]                                   
Hit:7 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                               
Hit:8 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
Get:9 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [284 kB]            
Ign:10 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic InRelease                                 
Ign:11 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic InRelease        
Err:12 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Err:13 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by phoenix277yt** [comment]
> @ryonakano here's a full log, im using the command for the ppa installation of the legacy option.
> `$ sudo add-apt-repository ppa:philip.scott/elementary-tweaks
> [sudo] password for daksh:
> system settings panel for elementary OS that lets you easily and safely customise your desktop's appearance https://github.com/elementary-tweaks/elementary-tweaks
> More info: https://launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks
> Press [ENTER] to continue or Ctrl-c to cancel adding it.
> 
> Hit:1 http://in.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease
> Hit:3 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease
> Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
> Hit:5 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease
> Get:6 http://packages.elementary.io/appcenter bionic InRelease [5,909 B]
> Hit:7 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease
> Hit:8 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
> Get:9 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [284 kB]
> Ign:10 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic InRelease
> Ign:11 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic InRelease
> Err:12 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Err:13 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release
> 404 Not Found [IP: 91.189.95.83 80]
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> `

it just links to the new one.

**Comment by ryonakano** [comment]
OK so we're facing two "not found" issues here:

```
Err:12 http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release 404 Not Found [IP: 91.189.95.83 80]
Err:13 http://ppa.launchpad.net/versable/elementary-update/ubuntu bionic Release 404 Not Found [IP: 91.189.95.83 80]
```

As far as looking at this log, fetching info of elementary Tweaks does not fail.

So could you run the following commands to remove PPAs that are not released to "bionic" which is the based Ubuntu version of elementary OS Hera:

```
sudo add-apt-repository -r ppa:versable/elementary-update
sudo add-apt-repository -r ppa:philip.scott/pantheon-tweaks
sudo apt update
```

According to [this page](https://launchpad.net/~versable/+archive/ubuntu/elementary-update), versable/elementary-update only supports elementary OS Luna, you can't use it on Hera unfortunatelly.

**Comment by phoenix277yt** [comment]
@ryonakano Thanks! It worked.

**Comment by ryonakano** [comment]
Glad to hear that! 🎉
