### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by printf83** [pantheon-tweaks/pantheon-tweaks#67]
`sudo apt install pantheon-tweaks
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pantheon-tweaks is already the newest version (1.0-0~202104120741~ubuntu6.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pantheon-tweaks : Depends: libgranite6 (>= 0.5) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
`

**Comment by ryonakano** [comment]
Hi, thank you for your reporting with a log! But unfortunately I can't reproduce your issue on my Odin Daily atm. Just want to make sure, are you using Odin Daily or possibly using Hera? Pantheon Tweaks is meant to be used on Odin or later, so it may not work on Hera.

**Comment by printf83** [comment]
I'm using elementary OS 5.1.7 Hera

**Comment by printf83** [comment]
thank you
