### ISSUE TITLE
No release file for focal

### ISSUE THREAD

**Issue by leonbollerup** [pantheon-tweaks/pantheon-tweaks#74]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C1D89326B1C71AB9

E: The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by ryonakano** [comment]
Hi, are you possibly trying to install Pantheon Tweaks on elementary OS Hera? We don't support elementary OS Hera or below and instead support Odin which is the next major version of elementary OS. Use elementary Tweaks instead for now and switch to Pantheon Tweaks when Odin is released.

The following commands should fix your issue and install the latest (working) version of elementary Tweaks:

```
sudo add-apt-repository -r -y ppa:mpstark/elementary-tweaks-daily
sudo add-apt-repository -r -y ppa:philip.scott/pantheon-tweaks
sudo add-apt-repository -y ppa:philip.scott/elementary-tweaks
sudo apt install -y elementary-tweaks
```
